language: node_js
node_js:
  - "0.10"

addons:
  sauce_connect:
    username: "hashspace"
    access_key: "9e47b05c-b1de-43ce-b9f0-dc64a3bc5f35"

before_install:
 - npm install --quiet -g gulp

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

script:
 - gulp test
